<?php 
    require('connection.php');
    require('comic.class.php');
    require('volume.class.php');
    require('chapter.class.php');
    require('user.class.php');
    require('author.class.php');
    require('authentified.class.php');
?>