-- MySQL Script generated by MySQL Workbench
-- Tue Jul 31 15:22:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bubbleUpDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bubbleUpDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bubbleUpDB` DEFAULT CHARACTER SET utf8 ;
USE `bubbleUpDB` ;

-- -----------------------------------------------------
-- Table `bubbleUpDB`.`comics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bubbleUpDB`.`comics` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(255) NOT NULL,
  `Synopsie` VARCHAR(255) NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Title_UNIQUE` (`Title` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bubbleUpDB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bubbleUpDB`.`users` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(255) NOT NULL,
  `Firstname` VARCHAR(255) NOT NULL,
  `Surname` VARCHAR(255) NOT NULL,
  `BirthDate` DATE NOT NULL,
  `Email` VARCHAR(254) NOT NULL,
  `EmailsValided` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bubbleUpDB`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bubbleUpDB`.`authors` (
  `comicId` INT NOT NULL,
  `userId` INT NOT NULL,
  INDEX `fk_authors_comics_idx` (`comicId` ASC) VISIBLE,
  INDEX `fk_authors_users1_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_authors_comics`
    FOREIGN KEY (`comicId`)
    REFERENCES `bubbleUpDB`.`comics` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_authors_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `bubbleUpDB`.`users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bubbleUpDB`.`narrativeArcs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bubbleUpDB`.`narrativeArcs` (
  `Id` INT NOT NULL,
  `Number` INT NOT NULL,
  `Title` VARCHAR(255) NOT NULL,
  `Synopsie` VARCHAR(255) NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NULL,
  `comicId` INT NOT NULL,
  INDEX `fk_narrativeArc_comics1_idx` (`comicId` ASC) VISIBLE,
  PRIMARY KEY (`Id`),
  CONSTRAINT `fk_narrativeArc_comics1`
    FOREIGN KEY (`comicId`)
    REFERENCES `bubbleUpDB`.`comics` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bubbleUpDB`.`volumes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bubbleUpDB`.`volumes` (
  `Id` INT NOT NULL,
  `Number` INT NOT NULL,
  `Title` VARCHAR(255) NOT NULL,
  `Synopsie` VARCHAR(255) NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NULL,
  `narrativeArcId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_volume_narrativeArc1_idx` (`narrativeArcId` ASC) VISIBLE,
  CONSTRAINT `fk_volume_narrativeArc1`
    FOREIGN KEY (`narrativeArcId`)
    REFERENCES `bubbleUpDB`.`narrativeArcs` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bubbleUpDB`.`chapters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bubbleUpDB`.`chapters` (
  `Id` INT NOT NULL,
  `Number` INT NOT NULL,
  `Title` VARCHAR(255) NOT NULL,
  `Synopsie` VARCHAR(255) NOT NULL,
  `Validated` TINYINT NOT NULL,
  `PublicationDate` DATE NULL,
  `volumeId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_chapters_volumes1_idx` (`volumeId` ASC) VISIBLE,
  CONSTRAINT `fk_chapters_volumes1`
    FOREIGN KEY (`volumeId`)
    REFERENCES `bubbleUpDB`.`volumes` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bubbleUpDB`.`comicStrips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bubbleUpDB`.`comicStrips` (
  `Id` INT NOT NULL,
  `Number` INT NOT NULL,
  `Path` VARCHAR(250) NOT NULL,
  `chapterId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_comicStrips_chapters1_idx` (`chapterId` ASC) VISIBLE,
  CONSTRAINT `fk_comicStrips_chapters1`
    FOREIGN KEY (`chapterId`)
    REFERENCES `bubbleUpDB`.`chapters` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bubbleUpDB`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bubbleUpDB`.`genre` (
  `Id` INT NOT NULL,
  `Label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bubbleUpDB`.`searchComics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bubbleUpDB`.`searchComics` (
  `genreId` INT NOT NULL,
  `comicId` INT NOT NULL,
  INDEX `fk_searchComics_genre1_idx` (`genreId` ASC) VISIBLE,
  INDEX `fk_searchComics_comics1_idx` (`comicId` ASC) VISIBLE,
  CONSTRAINT `fk_searchComics_genre1`
    FOREIGN KEY (`genreId`)
    REFERENCES `bubbleUpDB`.`genre` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_searchComics_comics1`
    FOREIGN KEY (`comicId`)
    REFERENCES `bubbleUpDB`.`comics` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `bubbleUpDB`;

DELIMITER $$
USE `bubbleUpDB`$$
CREATE DEFINER = CURRENT_USER TRIGGER `bubbleUpDB`.`chapters_BEFORE_UPDATE` BEFORE UPDATE ON `chapters` FOR EACH ROW
BEGIN
	IF (OLD.Valided = 0 OR NEW.Valided = 1) THEN
		SET NEW.PublicationDate = NOW();
	END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
